insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOTIMESRLDELFRACTSET', 'PMNOTIMESRLDELFRACTSET', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOTIMESRLADDTOACTSET', 'PMNOTIMESRLADDTOACTSET', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOTIMESRLREPINACTSET', 'PMNOTIMESRLREPINACTSET', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOTIMESCELLFAILADDTOACTSET', 'PMNOTIMESCELLFAILADDTOACTSET', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOCELLUPDATTEMPT', 'PMNOCELLUPDATTEMPT', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOCELLUPDSUCCESS', 'PMNOCELLUPDSUCCESS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOCELLDCHDISCONNECTNORMAL', 'PMNOCELLDCHDISCONNECTNORMAL', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOCELLFACHDISCONNECTNORMAL', 'PMNOCELLFACHDISCONNECTNORMAL', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOCELLDCHDISCONNECTABNORM', 'PMNOCELLDCHDISCONNECTABNORM', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOCELLFACHDISCONNECTABNORM', 'PMNOCELLFACHDISCONNECTABNORM', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOSPEECHDCHDISCNORMAL', 'PMNOSPEECHDCHDISCNORMAL', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOSPEECHDCHDISCABNORM', 'PMNOSPEECHDCHDISCABNORM', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOPACKETDCHDISCNORMAL', 'PMNOPACKETDCHDISCNORMAL', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOPACKETDCHDISCABNORM', 'PMNOPACKETDCHDISCABNORM', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOCS64DCHDISCNORMAL', 'PMNOCS64DCHDISCNORMAL', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOCS64DCHDISCABNORM', 'PMNOCS64DCHDISCABNORM', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMTOTNOUTRANREJRRCCONNREQ', 'PMTOTNOUTRANREJRRCCONNREQ', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOREJRRCCONNMPLOADC', 'PMNOREJRRCCONNMPLOADC', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOFSAMPASEUL', 'PMNOOFSAMPASEUL', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMOFSAMPASEUL', 'PMSUMOFSAMPASEUL', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOFSAMPASEDL', 'PMNOOFSAMPASEDL', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMOFSAMPASEDL', 'PMSUMOFSAMPASEDL', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMOFTIMESMEASOLDL', 'PMSUMOFTIMESMEASOLDL', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMOFTIMESMEASOLUL', 'PMSUMOFTIMESMEASOLUL', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOREQDENIEDADM', 'PMNOREQDENIEDADM', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOFAILEDAFTERADM', 'PMNOFAILEDAFTERADM', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOFSWDOWNNGADM', 'PMNOOFSWDOWNNGADM', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOFRLFORDRIFTINGUES', 'PMNOOFRLFORDRIFTINGUES', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOFRLFORNONDRIFTINGUES', 'PMNOOFRLFORNONDRIFTINGUES', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOFRETURNINGEMERGENCYCALLS', 'PMNOOFRETURNINGEMERGENCYCALLS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOFRETURNINGRRCCONN', 'PMNOOFRETURNINGRRCCONN', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNODIRRETRYSUCCESS', 'PMNODIRRETRYSUCCESS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOSYSRELSPEECHSOHO', 'PMNOSYSRELSPEECHSOHO', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOSYSRELSPEECHNEIGHBR', 'PMNOSYSRELSPEECHNEIGHBR', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOSYSRELSPEECHULSYNCH', 'PMNOSYSRELSPEECHULSYNCH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOFAILEDRABESTATTEMPTEXCEEDCONNLIMIT', 'COL_235', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOFAILEDRABESTATTEMPTLACKDLPWR', 'COL_236', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOFAILEDRABESTATTEMPTLACKDLCHNLCODE', 'COL_237', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOFAILEDRABESTATTEMPTLACKDLASE', 'COL_238', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOFAILEDRABESTATTEMPTLACKULASE', 'COL_239', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESCS64PS8RABESTABLISH', 'PMSAMPLESCS64PS8RABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMCS64PS8RABESTABLISH', 'PMSUMCS64PS8RABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOINCOMINGHSHARDHOSUCCESS', 'PMNOINCOMINGHSHARDHOSUCCESS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOUTGOINGHSHARDHOSUCCESS', 'PMNOOUTGOINGHSHARDHOSUCCESS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOHSCCATTEMPT', 'PMNOHSCCATTEMPT', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOHSCCSUCCESS', 'PMNOHSCCSUCCESS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESPSHSADCHRABESTABLISH', 'PMSAMPLESPSHSADCHRABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMPSHSADCHRABESTABLISH', 'PMSUMPSHSADCHRABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESPSSTR128PS8RABESTABLISH', 'COL_240', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMPSSTR128PS8RABESTABLISH', 'PMSUMPSSTR128PS8RABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMINACTIVITYPSSTREAMIDLE', 'PMINACTIVITYPSSTREAMIDLE', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESBESTCS12PSINTRABESTABLISH', 'COL_241', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMBESTCS12PSINTRABESTABLISH', 'PMSUMBESTCS12PSINTRABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESBESTCS64PSINTRABESTABLISH', 'COL_242', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMBESTCS64PSINTRABESTABLISH', 'PMSUMBESTCS64PSINTRABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMDOWNSWITCHATTEMPT', 'PMDOWNSWITCHATTEMPT', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMDOWNSWITCHSUCCESS', 'PMDOWNSWITCHSUCCESS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMULUPSWITCHSUCCESSMEDIUM', 'PMULUPSWITCHSUCCESSMEDIUM', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMULUPSWITCHATTEMPTMEDIUM', 'PMULUPSWITCHATTEMPTMEDIUM', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMUPSWITCHFACHHSSUCCESS', 'PMUPSWITCHFACHHSSUCCESS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMUPSWITCHFACHHSATTEMPT', 'PMUPSWITCHFACHHSATTEMPT', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMULUPSWITCHSUCCESSLOW', 'PMULUPSWITCHSUCCESSLOW', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMULUPSWITCHATTEMPTLOW', 'PMULUPSWITCHATTEMPTLOW', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMULUPSWITCHSUCCESSHIGH', 'PMULUPSWITCHSUCCESSHIGH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMULUPSWITCHATTEMPTHIGH', 'PMULUPSWITCHATTEMPTHIGH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMDLUPSWITCHSUCCESSHS', 'PMDLUPSWITCHSUCCESSHS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMDLUPSWITCHATTEMPTHS', 'PMDLUPSWITCHATTEMPTHS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMCHSWITCHATTEMPTFACHURA', 'PMCHSWITCHATTEMPTFACHURA', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMCHSWITCHSUCCFACHURA', 'PMCHSWITCHSUCCFACHURA', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMCHSWITCHATTEMPTURAFACH', 'PMCHSWITCHATTEMPTURAFACH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMCHSWITCHSUCCURAFACH', 'PMCHSWITCHSUCCURAFACH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNONORMALRABRELEASEPACKETURA', 'PMNONORMALRABRELEASEPACKETURA', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOSYSTEMRABRELEASEPACKETURA', 'PMNOSYSTEMRABRELEASEPACKETURA', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOURAUPDATTEMPT', 'PMNOURAUPDATTEMPT', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOURAUPDSUCCESS', 'PMNOURAUPDSUCCESS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMEULHARQTRANSMTTI10FAILURE', 'PMEULHARQTRANSMTTI10FAILURE', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMULUPSWITCHATTEMPTEUL', 'PMULUPSWITCHATTEMPTEUL', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMULUPSWITCHSUCCESSEUL', 'PMULUPSWITCHSUCCESSEUL', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESPSEULRABESTABLISH', 'PMSAMPLESPSEULRABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMPSEULRABESTABLISH', 'PMSUMPSEULRABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESULRSSI', 'PMSAMPLESULRSSI', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMULRSSI', 'PMSUMULRSSI', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMDLUPSWITCHATTEMPTLOW', 'PMDLUPSWITCHATTEMPTLOW', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMDLUPSWITCHATTEMPTMEDIUM', 'PMDLUPSWITCHATTEMPTMEDIUM', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMDLUPSWITCHATTEMPTHIGH', 'PMDLUPSWITCHATTEMPTHIGH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMDLUPSWITCHSUCCESSLOW', 'PMDLUPSWITCHSUCCESSLOW', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMDLUPSWITCHSUCCESSMEDIUM', 'PMDLUPSWITCHSUCCESSMEDIUM', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMDLUPSWITCHSUCCESSHIGH', 'PMDLUPSWITCHSUCCESSHIGH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNODISCARDSDUDTCHDLPSSTREAMING', 'COL_243', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORECEIVEDSDUDTCHDLPSSTREAMING', 'COL_244', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORECEIVEDSDUDTCHULPSSTREAMING', 'COL_245', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOFAILEDRABESTATTEMPTLACKDLHWBEST', 'COL_246', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOFAILEDRABESTATTEMPTLACKULHWBEST', 'COL_247', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOFAILEDRABESTATTEMPTLACKULHW', 'COL_248', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOFAILEDRABESTATTEMPTLACKDLHW', 'COL_249', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNODISCARDSDUDTCHHSPSSTREAM', 'PMNODISCARDSDUDTCHHSPSSTREAM', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORECEIVEDSDUDTCHHSPSSTREAM', 'PMNORECEIVEDSDUDTCHHSPSSTREAM', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOPSSTREAMHSCCATTEMPT', 'PMNOPSSTREAMHSCCATTEMPT', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOPSSTREAMHSCCSUCCESS', 'PMNOPSSTREAMHSCCSUCCESS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTBLOCKTNPSSTREAMHSBEST', 'COL_250', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTBLOCKTNSPEECHBEST', 'PMNORABESTBLOCKTNSPEECHBEST', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTBLOCKTNCS57BEST', 'PMNORABESTBLOCKTNCS57BEST', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTBLOCKTNCS64BEST', 'PMNORABESTBLOCKTNCS64BEST', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTBLOCKTNPSSTRNONHSBEST', 'COL_251', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTBLOCKTNPSINTNONHSBEST', 'COL_252', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTBLOCKTNPSINTHSBEST', 'PMNORABESTBLOCKTNPSINTHSBEST', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTBLOCKTNPSSTRHS', 'PMNORABESTBLOCKTNPSSTRHS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTBLOCKTNSPEECH', 'PMNORABESTBLOCKTNSPEECH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTBLOCKTNCS57', 'PMNORABESTBLOCKTNCS57', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTBLOCKTNCS64', 'PMNORABESTBLOCKTNCS64', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTBLOCKTNPSSTRNONHS', 'PMNORABESTBLOCKTNPSSTRNONHS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTBLOCKTNPSINTNONHS', 'PMNORABESTBLOCKTNPSINTNONHS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTBLOCKTNPSINTHS', 'PMNORABESTBLOCKTNPSINTHS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORRCCONNREQBLOCKTNCS', 'PMNORRCCONNREQBLOCKTNCS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORRCCONNREQBLOCKTNPS', 'PMNORRCCONNREQBLOCKTNPS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTBLOCKNODESPEECHBEST', 'PMNORABESTBLOCKNODESPEECHBEST', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTBLOCKNODECS57BEST', 'PMNORABESTBLOCKNODECS57BEST', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTBLOCKNODECS64BEST', 'PMNORABESTBLOCKNODECS64BEST', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTBLKNODEPSINTNONHSBEST', 'COL_253', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTBLOCKNODEPSINTHSBEST', 'PMNORABESTBLOCKNODEPSINTHSBEST', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTBLOCKNODEPSSTRHSBEST', 'PMNORABESTBLOCKNODEPSSTRHSBEST', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTBLKNODEPSSTRNONHSBEST', 'COL_254', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORRCCONNREQBLOCKNODECS', 'PMNORRCCONNREQBLOCKNODECS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORRCCONNREQBLOCKNODEPS', 'PMNORRCCONNREQBLOCKNODEPS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMSQRULRSSI', 'PMSUMSQRULRSSI', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMDLCODE', 'PMSUMDLCODE', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMSQRDLCODE', 'PMSUMSQRDLCODE', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESDLCODE', 'PMSAMPLESDLCODE', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOFAILEDRRCCONNECTREQCSHW', 'PMNOFAILEDRRCCONNECTREQCSHW', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOFAILEDRRCCONNECTREQPSHW', 'PMNOFAILEDRRCCONNECTREQPSHW', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOFAILEDRRCCONNECTREQHW', 'PMNOFAILEDRRCCONNECTREQHW', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMDCHULRLCUSERPACKETTHP', 'PMDCHULRLCUSERPACKETTHP', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMDCHDLRLCUSERPACKETTHP', 'PMDCHDLRLCUSERPACKETTHP', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMEULHARQTRANSMTTI10PSINTERACTIVE', 'COL_255', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMEULHARQTRANSMTTI10SRB', 'PMEULHARQTRANSMTTI10SRB', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMPACKETDLDELAY', 'PMSUMPACKETDLDELAY', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESPACKETDLDELAY', 'PMSAMPLESPACKETDLDELAY', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMEULHARQTRANSMTTI2PSRABS', 'PMEULHARQTRANSMTTI2PSRABS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMEULHARQTRANSMTTI2SRB', 'PMEULHARQTRANSMTTI2SRB', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOCSSTREAMDCHDISCNORMAL', 'PMNOCSSTREAMDCHDISCNORMAL', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOCSSTREAMDCHDISCABNORM', 'PMNOCSSTREAMDCHDISCABNORM', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMTOTNORRCCONNECTREQ', 'PMTOTNORRCCONNECTREQ', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMTOTNORRCCONNECTREQSUCCESS', 'PMTOTNORRCCONNECTREQSUCCESS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMTOTNORRCCONNECTREQCS', 'PMTOTNORRCCONNECTREQCS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMTOTNORRCCONNECTREQCSSUCC', 'PMTOTNORRCCONNECTREQCSSUCC', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMTOTNORRCCONNECTREQPS', 'PMTOTNORRCCONNECTREQPS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMTOTNORRCCONNECTREQPSSUCC', 'PMTOTNORRCCONNECTREQPSSUCC', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMCHSWITCHFACHIDLE', 'PMCHSWITCHFACHIDLE', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESCS12RABESTABLISH', 'PMSAMPLESCS12RABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMCS12RABESTABLISH', 'PMSUMCS12RABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOLOADSHARINGRRCCONN', 'PMNOLOADSHARINGRRCCONN', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOPSSTREAM64PS8DCHDISCNORMAL', 'PMNOPSSTREAM64PS8DCHDISCNORMAL', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOPSSTREAM64PS8DCHDISCABNORM', 'PMNOPSSTREAM64PS8DCHDISCABNORM', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESBESTCS12ESTABLISH', 'PMSAMPLESBESTCS12ESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMBESTCS12ESTABLISH', 'PMSUMBESTCS12ESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNODIRRETRYATT', 'PMNODIRRETRYATT', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMCELLDOWNTIMEAUTO', 'PMCELLDOWNTIMEAUTO', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMCELLDOWNTIMEMAN', 'PMCELLDOWNTIMEMAN', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMTOTALTIMEULCELLCONG', 'PMTOTALTIMEULCELLCONG', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMTOTALTIMEDLCELLCONG', 'PMTOTALTIMEDLCELLCONG', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOFNONHOREQDENIEDSPEECH', 'PMNOOFNONHOREQDENIEDSPEECH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOFNONHOREQDENIEDCS', 'PMNOOFNONHOREQDENIEDCS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOFNONHOREQDENIEDINTERACTIVE', 'COL_256', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTABLISHATTEMPTSPEECH', 'PMNORABESTABLISHATTEMPTSPEECH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTABLISHATTEMPTCS64', 'PMNORABESTABLISHATTEMPTCS64', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTABLISHATTEMPTCS57', 'PMNORABESTABLISHATTEMPTCS57', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTABLISHATTEMPTPACKETINTERACTIVE', 'COL_257', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTABLISHATTEMPTPACKETSTREAM', 'COL_258', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTABLISHSUCCESSSPEECH', 'PMNORABESTABLISHSUCCESSSPEECH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTABLISHSUCCESSCS64', 'PMNORABESTABLISHSUCCESSCS64', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTABLISHSUCCESSCS57', 'PMNORABESTABLISHSUCCESSCS57', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTABLISHSUCCESSPACKETINTERACTIVE', 'COL_259', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTABLISHSUCCESSPACKETSTREAM', 'COL_260', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNONORMALRABRELEASEPACKET', 'PMNONORMALRABRELEASEPACKET', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNONORMALRABRELEASESPEECH', 'PMNONORMALRABRELEASESPEECH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOSYSTEMRABRELEASEPACKET', 'PMNOSYSTEMRABRELEASEPACKET', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOSYSTEMRABRELEASESPEECH', 'PMNOSYSTEMRABRELEASESPEECH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNONORMALRABRELEASEPACKETSTREAM', 'COL_261', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOSYSTEMRABRELEASEPACKETSTREAM', 'COL_262', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNONORMALRABRELEASECSSTREAM', 'PMNONORMALRABRELEASECSSTREAM', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNONORMALRABRELEASECS64', 'PMNONORMALRABRELEASECS64', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOSYSTEMRABRELEASECSSTREAM', 'PMNOSYSTEMRABRELEASECSSTREAM', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOSYSTEMRABRELEASECS64', 'PMNOSYSTEMRABRELEASECS64', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOFNONHOREQDENIEDPSSTREAMING', 'COL_263', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTABLISHATTEMPTPACKETINTERACTIVEHS', 'COL_264', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTABLISHSUCCESSPACKETINTERACTIVEHS', 'COL_265', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNONORMALRBRELEASEHS', 'PMNONORMALRBRELEASEHS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOSYSTEMRBRELEASEHS', 'PMNOSYSTEMRBRELEASEHS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOINCOMINGHSHARDHOATTEMPT', 'PMNOINCOMINGHSHARDHOATTEMPT', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOUTGOINGHSHARDHOATTEMPT', 'PMNOOUTGOINGHSHARDHOATTEMPT', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOHSHARDHORETURNOLDCHSOURCE', 'PMNOHSHARDHORETURNOLDCHSOURCE', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOHSHARDHORETURNOLDCHTARGET', 'PMNOHSHARDHORETURNOLDCHTARGET', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOFNONHOREQDENIEDHS', 'PMNOOFNONHOREQDENIEDHS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESBESTPSHSADCHRABESTABLISH', 'COL_266', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMBESTPSHSADCHRABESTABLISH', 'PMSUMBESTPSHSADCHRABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTABLISHSUCCESSPACKETSTREAM128', 'COL_267', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTABLISHATTEMPTPACKETSTREAM128', 'COL_268', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESBESTPSSTR128PS8RABESTABLISH', 'COL_269', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMBESTPSSTR128PS8RABESTABLISH', 'COL_270', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNONORMALRABRELEASEPACKETSTREAM128', 'COL_271', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOSYSTEMRABRELEASEPACKETSTREAM128', 'COL_272', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOFNONHOREQDENIEDPSSTR128', 'PMNOOFNONHOREQDENIEDPSSTR128', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESBESTCS57RABESTABLISH', 'PMSAMPLESBESTCS57RABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMBESTCS57RABESTABLISH', 'PMSUMBESTCS57RABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESBESTCS64RABESTABLISH', 'PMSAMPLESBESTCS64RABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMBESTCS64RABESTABLISH', 'PMSUMBESTCS64RABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESFACHPSINTRABESTABLISH', 'PMSAMPLESFACHPSINTRABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMFACHPSINTRABESTABLISH', 'PMSUMFACHPSINTRABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESBESTDCHPSINTRABESTABLISH', 'COL_273', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMBESTDCHPSINTRABESTABLISH', 'PMSUMBESTDCHPSINTRABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESBESTPSSTR64PS8RABESTABLISH', 'COL_274', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMBESTPSSTR64PS8RABESTABLISH', 'COL_275', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESDCHULRLCTOTPACKETTHP', 'PMSAMPLESDCHULRLCTOTPACKETTHP', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMDCHULRLCTOTPACKETTHP', 'PMSUMDCHULRLCTOTPACKETTHP', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESDCHDLRLCTOTPACKETTHP', 'PMSAMPLESDCHDLRLCTOTPACKETTHP', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMDCHDLRLCTOTPACKETTHP', 'PMSUMDCHDLRLCTOTPACKETTHP', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESDCHULRLCUSERPACKETTHP', 'PMSAMPLESDCHULRLCUSERPACKETTHP', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMDCHULRLCUSERPACKETTHP', 'PMSUMDCHULRLCUSERPACKETTHP', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESDCHDLRLCUSERPACKETTHP', 'PMSAMPLESDCHDLRLCUSERPACKETTHP', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMDCHDLRLCUSERPACKETTHP', 'PMSUMDCHDLRLCUSERPACKETTHP', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORRCCSREQDENIEDADM', 'PMNORRCCSREQDENIEDADM', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESPSINTERACTIVE', 'PMSAMPLESPSINTERACTIVE', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMPSINTERACTIVE', 'PMSUMPSINTERACTIVE', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTABLISHATTEMPTPACKETINTERACTIVEEUL', 'COL_276', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTABLISHSUCCESSPACKETINTERACTIVEEUL', 'COL_277', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOSYSTEMRBRELEASEEUL', 'PMNOSYSTEMRBRELEASEEUL', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNONORMALRBRELEASEEUL', 'PMNONORMALRBRELEASEEUL', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESBESTPSEULRABESTABLISH', 'PMSAMPLESBESTPSEULRABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMBESTPSEULRABESTABLISH', 'PMSUMBESTPSEULRABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMRABESTABLISHECATTEMPT', 'PMRABESTABLISHECATTEMPT', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMRABESTABLISHECSUCCESS', 'PMRABESTABLISHECSUCCESS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOFNONHOREQDENIEDEUL', 'PMNOOFNONHOREQDENIEDEUL', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMULRLCUSERTHPPSSTREAM16', 'PMSUMULRLCUSERTHPPSSTREAM16', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESULRLCUSERTHPPSSTREAM16', 'COL_278', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMDLRLCUSERTHPPSSTREAM64', 'PMSUMDLRLCUSERTHPPSSTREAM64', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESDLRLCUSERTHPPSSTREAM64', 'COL_279', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMDLRLCUSERTHPPSSTREAM128', 'PMSUMDLRLCUSERTHPPSSTREAM128', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESDLRLCUSERTHPPSSTREAM128', 'COL_280', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTATTEMPTPSSTREAMHS', 'PMNORABESTATTEMPTPSSTREAMHS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTSUCCESSPSSTREAMHS', 'PMNORABESTSUCCESSPSSTREAMHS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNONORMALRABRELEASEPSSTREAMHS', 'PMNONORMALRABRELEASEPSSTREAMHS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOSYSTEMRABRELEASEPSSTREAMHS', 'PMNOSYSTEMRABRELEASEPSSTREAMHS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESPSSTREAMHSRABEST', 'PMSAMPLESPSSTREAMHSRABEST', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMPSSTREAMHSRABEST', 'PMSUMPSSTREAMHSRABEST', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESBESTPSSTREAMHSRABEST', 'PMSAMPLESBESTPSSTREAMHSRABEST', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMBESTPSSTREAMHSRABEST', 'PMSUMBESTPSSTREAMHSRABEST', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMDLRLCUSERTHPPSSTREAMHS', 'PMSUMDLRLCUSERTHPPSSTREAMHS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESDLRLCUSERTHPPSSTREAMHS', 'COL_281', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMULRLCUSERTHPPSSTREAM32', 'PMSUMULRLCUSERTHPPSSTREAM32', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESULRLCUSERTHPPSSTREAM32', 'COL_282', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOINCOMINGPSSTREAMHSHHOATTEMPT', 'COL_283', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOINCOMINGPSSTREAMHSHHOSUCCESS', 'COL_284', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOUTGOINGPSSTREAMHSHHOATTEMPT', 'COL_285', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOUTGOINGPSSTREAMHSHHOSUCCESS', 'COL_286', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOPSSTREAMHSHHORETURNOLDSOURCE', 'COL_287', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOPSSTREAMHSHHORETURNOLDTARGET', 'COL_288', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMULRLCUSERTHPPSSTREAM128', 'PMSUMULRLCUSERTHPPSSTREAM128', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESULRLCUSERTHPPSSTREAM128', 'COL_289', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOLOADSHARINGRRCCONNCS', 'PMNOLOADSHARINGRRCCONNCS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOLOADSHARINGRRCCONNPS', 'PMNOLOADSHARINGRRCCONNPS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTATTEMPTPSINTNONHS', 'PMNORABESTATTEMPTPSINTNONHS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTSUCCESSPSINTNONHS', 'PMNORABESTSUCCESSPSINTNONHS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMPACKETLATENCY', 'PMSUMPACKETLATENCY', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESPACKETLATENCY', 'PMSAMPLESPACKETLATENCY', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMPACKETLATENCYPSSTREAMHS', 'PMSUMPACKETLATENCYPSSTREAMHS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESPACKETLATENCYPSSTREAMHS', 'COL_290', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMDLTRAFFICVOLUMEPSINTHS', 'PMDLTRAFFICVOLUMEPSINTHS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMULTRAFFICVOLUMEPSINTEUL', 'PMULTRAFFICVOLUMEPSINTEUL', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMFAULTYTRANSPORTBLOCKSBCUL', 'PMFAULTYTRANSPORTBLOCKSBCUL', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMTRANSPORTBLOCKSBCUL', 'PMTRANSPORTBLOCKSBCUL', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOFTERMSPEECHCONG', 'PMNOOFTERMSPEECHCONG', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMENABLEEULHHOATTEMPT', 'PMENABLEEULHHOATTEMPT', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMENABLEEULHHOSUCCESS', 'PMENABLEEULHHOSUCCESS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMENABLEHSHHOATTEMPT', 'PMENABLEHSHHOATTEMPT', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMENABLEHSHHOSUCCESS', 'PMENABLEHSHHOSUCCESS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOINCOMINGEULHARDHOATTEMPT', 'PMNOINCOMINGEULHARDHOATTEMPT', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOINCOMINGEULHARDHOSUCCESS', 'PMNOINCOMINGEULHARDHOSUCCESS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOUTGOINGEULHARDHOATTEMPT', 'PMNOOUTGOINGEULHARDHOATTEMPT', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOUTGOINGEULHARDHOSUCCESS', 'PMNOOUTGOINGEULHARDHOSUCCESS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORRCPSREQDENIEDADM', 'PMNORRCPSREQDENIEDADM', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMTOTNOTERMRRCCONNECTREQPS', 'PMTOTNOTERMRRCCONNECTREQPS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMTOTNOTERMRRCCONNECTREQPSSUCC', 'PMTOTNOTERMRRCCONNECTREQPSSUCC', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMTOTNOTERMRRCCONNECTREQSUCC', 'PMTOTNOTERMRRCCONNECTREQSUCC', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMTOTALTIMEHSDSCHOVERLOAD', 'PMTOTALTIMEHSDSCHOVERLOAD', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOPAGINGTYPE1ATTEMPTCS', 'PMNOPAGINGTYPE1ATTEMPTCS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOPAGINGTYPE1ATTEMPTPS', 'PMNOPAGINGTYPE1ATTEMPTPS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMTOTNOTERMRRCCONNECTREQCS', 'PMTOTNOTERMRRCCONNECTREQCS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMDLTRAFFICVOLUMEAMR4750', 'PMDLTRAFFICVOLUMEAMR4750', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMDLTRAFFICVOLUMEAMR5900', 'PMDLTRAFFICVOLUMEAMR5900', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMDLTRAFFICVOLUMEAMR7950', 'PMDLTRAFFICVOLUMEAMR7950', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMDLTRAFFICVOLUMEAMRNBMM', 'PMDLTRAFFICVOLUMEAMRNBMM', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMDLTRAFFICVOLUMEAMRWB', 'PMDLTRAFFICVOLUMEAMRWB', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMDLTRAFFICVOLUMECS12', 'PMDLTRAFFICVOLUMECS12', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMDLTRAFFICVOLUMECS57', 'PMDLTRAFFICVOLUMECS57', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMDLTRAFFICVOLUMECS64', 'PMDLTRAFFICVOLUMECS64', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMDLTRAFFICVOLUMEPS128', 'PMDLTRAFFICVOLUMEPS128', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMDLTRAFFICVOLUMEPS16', 'PMDLTRAFFICVOLUMEPS16', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMDLTRAFFICVOLUMEPS384', 'PMDLTRAFFICVOLUMEPS384', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMDLTRAFFICVOLUMEPS64', 'PMDLTRAFFICVOLUMEPS64', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMDLTRAFFICVOLUMEPS8', 'PMDLTRAFFICVOLUMEPS8', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMDLTRAFFICVOLUMEPSCOMMON', 'PMDLTRAFFICVOLUMEPSCOMMON', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMDLTRAFFICVOLUMEPSSTR128', 'PMDLTRAFFICVOLUMEPSSTR128', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMDLTRAFFICVOLUMEPSSTR16', 'PMDLTRAFFICVOLUMEPSSTR16', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMDLTRAFFICVOLUMEPSSTR64', 'PMDLTRAFFICVOLUMEPSSTR64', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMDLTRAFFICVOLUMEPSSTRHS', 'PMDLTRAFFICVOLUMEPSSTRHS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMEULTODCHATTEMPT', 'PMEULTODCHATTEMPT', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMEULTODCHSUCCESS', 'PMEULTODCHSUCCESS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMHSTODCHATTEMPT', 'PMHSTODCHATTEMPT', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMHSTODCHSUCCESS', 'PMHSTODCHSUCCESS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOEULCCATTEMPT', 'PMNOEULCCATTEMPT', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOEULCCSUCCESS', 'PMNOEULCCSUCCESS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOINCSIRATHOADMFAIL', 'PMNOINCSIRATHOADMFAIL', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOINCSIRATHOATT', 'PMNOINCSIRATHOATT', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOINCSIRATHOSUCCESS', 'PMNOINCSIRATHOSUCCESS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNONORMALRABRELEASEAMRNB', 'PMNONORMALRABRELEASEAMRNB', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNONORMALRABRELEASEAMRWB', 'PMNONORMALRABRELEASEAMRWB', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOPAGINGATTEMPTCNINITDCCH', 'PMNOPAGINGATTEMPTCNINITDCCH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOPAGINGTYPE1ATTEMPT', 'PMNOPAGINGTYPE1ATTEMPT', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORLDENIEDADM', 'PMNORLDENIEDADM', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORRCREQDENIEDADM', 'PMNORRCREQDENIEDADM', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOSYSTEMRABRELEASEAMRNB', 'PMNOSYSTEMRABRELEASEAMRNB', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOSYSTEMRABRELEASEAMRWB', 'PMNOSYSTEMRABRELEASEAMRWB', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMRLADDATTEMPTSBESTCELLCSCONVERS', 'COL_291', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMRLADDATTEMPTSBESTCELLPACKETHIGH', 'COL_292', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMRLADDATTEMPTSBESTCELLPACKETLOW', 'COL_293', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMRLADDATTEMPTSBESTCELLSPEECH', 'PMRLADDATTEMPTSBESTCELLSPEECH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMRLADDATTEMPTSBESTCELLSTANDALONE', 'COL_294', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMRLADDATTEMPTSBESTCELLSTREAM', 'PMRLADDATTEMPTSBESTCELLSTREAM', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMRLADDSUCCESSBESTCELLCSCONVERS', 'COL_295', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMRLADDSUCCESSBESTCELLPACKETHIGH', 'COL_296', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMRLADDSUCCESSBESTCELLPACKETLOW', 'COL_297', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMRLADDSUCCESSBESTCELLSPEECH', 'PMRLADDSUCCESSBESTCELLSPEECH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMRLADDSUCCESSBESTCELLSTANDALONE', 'COL_298', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMRLADDSUCCESSBESTCELLSTREAM', 'PMRLADDSUCCESSBESTCELLSTREAM', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESAMR12200RABESTABLISH', 'PMSAMPLESAMR12200RABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESAMR4750RABESTABLISH', 'PMSAMPLESAMR4750RABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESAMR5900RABESTABLISH', 'PMSAMPLESAMR5900RABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESAMR7950RABESTABLISH', 'PMSAMPLESAMR7950RABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESAMRNBMMRABESTABLISH', 'PMSAMPLESAMRNBMMRABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESAMRWBRABESTABLISH', 'PMSAMPLESAMRWBRABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESBESTAMR12200RABESTABLISH', 'COL_299', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESBESTAMR4750RABESTABLISH', 'COL_300', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESBESTAMR5900RABESTABLISH', 'COL_301', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESBESTAMR7950RABESTABLISH', 'COL_302', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESBESTAMRNBMMRABESTABLISH', 'COL_303', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESBESTAMRWBRABESTABLISH', 'PMSAMPLESBESTAMRWBRABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESUESWITH1RLS1RLINACTSET', 'COL_304', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESUESWITH1RLS2RLINACTSET', 'COL_305', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESUESWITH1RLS3RLINACTSET', 'COL_306', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESUESWITH2RLS2RLINACTSET', 'COL_307', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESUESWITH2RLS3RLINACTSET', 'COL_308', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESUESWITH2RLS4RLINACTSET', 'COL_309', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESUESWITH3RLS3RLINACTSET', 'COL_310', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESUESWITH3RLS4RLINACTSET', 'COL_311', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESUESWITH4RLS4RLINACTSET', 'COL_312', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMAMR12200RABESTABLISH', 'PMSUMAMR12200RABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMAMR4750RABESTABLISH', 'PMSUMAMR4750RABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMAMR5900RABESTABLISH', 'PMSUMAMR5900RABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMAMR7950RABESTABLISH', 'PMSUMAMR7950RABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMAMRNBMMRABESTABLISH', 'PMSUMAMRNBMMRABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMAMRWBRABESTABLISH', 'PMSUMAMRWBRABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMBESTAMR12200RABESTABLISH', 'PMSUMBESTAMR12200RABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMBESTAMR4750RABESTABLISH', 'PMSUMBESTAMR4750RABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMBESTAMR5900RABESTABLISH', 'PMSUMBESTAMR5900RABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMBESTAMR7950RABESTABLISH', 'PMSUMBESTAMR7950RABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMBESTAMRNBMMRABESTABLISH', 'PMSUMBESTAMRNBMMRABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMBESTAMRWBRABESTABLISH', 'PMSUMBESTAMRWBRABESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMUESWITH1RLS1RLINACTSET', 'PMSUMUESWITH1RLS1RLINACTSET', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMUESWITH1RLS2RLINACTSET', 'PMSUMUESWITH1RLS2RLINACTSET', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMUESWITH1RLS3RLINACTSET', 'PMSUMUESWITH1RLS3RLINACTSET', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMUESWITH2RLS2RLINACTSET', 'PMSUMUESWITH2RLS2RLINACTSET', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMUESWITH2RLS3RLINACTSET', 'PMSUMUESWITH2RLS3RLINACTSET', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMUESWITH2RLS4RLINACTSET', 'PMSUMUESWITH2RLS4RLINACTSET', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMUESWITH3RLS3RLINACTSET', 'PMSUMUESWITH3RLS3RLINACTSET', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMUESWITH3RLS4RLINACTSET', 'PMSUMUESWITH3RLS4RLINACTSET', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMUESWITH4RLS4RLINACTSET', 'PMSUMUESWITH4RLS4RLINACTSET', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMTOTNORRCCONNECTATTIRATCCORDER', 'COL_313', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMTOTNORRCCONNECTATTIRATCELLRESEL', 'COL_314', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMTOTNORRCCONNECTSUCCESSIRATCCORDER', 'COL_315', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMTOTNORRCCONNECTSUCCESSIRATCELLRESEL', 'COL_316', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMTOTNOTERMRRCCONNECTREQ', 'PMTOTNOTERMRRCCONNECTREQ', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMTOTNOTERMRRCCONNECTREQCSSUCC', 'PMTOTNOTERMRRCCONNECTREQCSSUCC', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMULTRAFFICVOLUMEAMR4750', 'PMULTRAFFICVOLUMEAMR4750', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMULTRAFFICVOLUMEAMR5900', 'PMULTRAFFICVOLUMEAMR5900', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMULTRAFFICVOLUMEAMR7950', 'PMULTRAFFICVOLUMEAMR7950', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMULTRAFFICVOLUMEAMRNBMM', 'PMULTRAFFICVOLUMEAMRNBMM', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMULTRAFFICVOLUMEAMRWB', 'PMULTRAFFICVOLUMEAMRWB', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMULTRAFFICVOLUMECS12', 'PMULTRAFFICVOLUMECS12', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMULTRAFFICVOLUMECS57', 'PMULTRAFFICVOLUMECS57', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMULTRAFFICVOLUMECS64', 'PMULTRAFFICVOLUMECS64', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMULTRAFFICVOLUMEPS128', 'PMULTRAFFICVOLUMEPS128', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMULTRAFFICVOLUMEPS16', 'PMULTRAFFICVOLUMEPS16', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMULTRAFFICVOLUMEPS384', 'PMULTRAFFICVOLUMEPS384', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMULTRAFFICVOLUMEPS64', 'PMULTRAFFICVOLUMEPS64', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMULTRAFFICVOLUMEPS8', 'PMULTRAFFICVOLUMEPS8', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMULTRAFFICVOLUMEPSCOMMON', 'PMULTRAFFICVOLUMEPSCOMMON', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMULTRAFFICVOLUMEPSSTR128', 'PMULTRAFFICVOLUMEPSSTR128', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMULTRAFFICVOLUMEPSSTR16', 'PMULTRAFFICVOLUMEPSSTR16', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMULTRAFFICVOLUMEPSSTR32', 'PMULTRAFFICVOLUMEPSSTR32', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMRRCONLYESTABLISH', 'PMSUMRRCONLYESTABLISH', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMSRBONLY34', 'PMSUMSRBONLY34', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMTOTNORRCCONNECTFAILCONGIRATCCORDER', 'COL_317', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMTOTNORRCCONNECTFAILCONGIRATCELLRESEL', 'COL_318', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMTOTNORRCCONNECTREQSMS', 'PMTOTNORRCCONNECTREQSMS', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNONORMALRELEASESRBONLY136', 'PMNONORMALRELEASESRBONLY136', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNONORMALRELEASESRBONLY34', 'PMNONORMALRELEASESRBONLY34', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOPSSTREAM128PS8DCHDISCABNORM', 'COL_319', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOSYSTEMRELEASESRBONLY136', 'PMNOSYSTEMRELEASESRBONLY136', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOSYSTEMRELEASESRBONLY34', 'PMNOSYSTEMRELEASESRBONLY34', 'CLT_PM_W_ERIC_UTRANCELL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOATTOUTIRATHOCS57', 'PMNOATTOUTIRATHOCS57', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOATTOUTIRATHOMULTI', 'PMNOATTOUTIRATHOMULTI', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOATTOUTIRATHOSPEECH', 'PMNOATTOUTIRATHOSPEECH', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOATTOUTIRATHOSTANDALONE', 'PMNOATTOUTIRATHOSTANDALONE', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOATTOUTSBHOSPEECH', 'PMNOATTOUTSBHOSPEECH', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOFAILOUTIRATHOCS57GSMFAILURE', 'COL_320', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOFAILOUTIRATHOCS57RETURNOLDCHNOTPHYCHFAIL', 'COL_321', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOFAILOUTIRATHOCS57RETURNOLDCHPHYCHFAIL', 'COL_322', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOFAILOUTIRATHOCS57UEREJECTION', 'COL_323', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOFAILOUTIRATHOMULTIGSMFAILURE', 'COL_324', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOFAILOUTIRATHOMULTIRETURNOLDCHNOTPHYCHFAIL', 'COL_325', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOFAILOUTIRATHOMULTIRETURNOLDCHPHYCHFAIL', 'COL_326', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOFAILOUTIRATHOMULTIUEREJECTION', 'COL_327', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOFAILOUTIRATHOSPEECHGSMFAILURE', 'COL_328', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOFAILOUTIRATHOSPEECHRETURNOLDCHNOTPHYCHFAIL', 'COL_329', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOFAILOUTIRATHOSPEECHRETURNOLDCHPHYCHFAIL', 'COL_330', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOFAILOUTIRATHOSPEECHUEREJECTION', 'COL_331', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOFAILOUTIRATHOSTANDALONEGSMFAILURE', 'COL_332', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOFAILOUTIRATHOSTANDALONERETURNOLDCHNOTPHYCHFAIL', 'COL_333', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOFAILOUTIRATHOSTANDALONERETURNOLDCHPHYCHFAIL', 'COL_334', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOFAILOUTIRATHOSTANDALONEUEREJECTION', 'COL_335', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOFAILOUTSBHOSPEECHGSMFAILURE', 'COL_336', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOFAILOUTSBHOSPEECHRETURNOLDCHNOTPHYCHFAIL', 'COL_337', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOFAILOUTSBHOSPEECHRETURNOLDCHPHYCHFAIL', 'COL_338', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOFAILOUTSBHOSPEECHUEREJECTION', 'COL_339', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOUTIRATCCATT', 'PMNOOUTIRATCCATT', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOUTIRATCCATTEUL', 'PMNOOUTIRATCCATTEUL', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOUTIRATCCATTHS', 'PMNOOUTIRATCCATTHS', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOUTIRATCCRETURNOLDCH', 'PMNOOUTIRATCCRETURNOLDCH', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOUTIRATCCRETURNOLDCHEUL', 'PMNOOUTIRATCCRETURNOLDCHEUL', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOUTIRATCCRETURNOLDCHHS', 'PMNOOUTIRATCCRETURNOLDCHHS', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOUTIRATCCSUCCESS', 'PMNOOUTIRATCCSUCCESS', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOUTIRATCCSUCCESSEUL', 'PMNOOUTIRATCCSUCCESSEUL', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOUTIRATCCSUCCESSHS', 'PMNOOUTIRATCCSUCCESSHS', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOSUCCESSOUTIRATHOCS57', 'PMNOSUCCESSOUTIRATHOCS57', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOSUCCESSOUTIRATHOMULTI', 'PMNOSUCCESSOUTIRATHOMULTI', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOSUCCESSOUTIRATHOSPEECH', 'PMNOSUCCESSOUTIRATHOSPEECH', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOSUCCESSOUTIRATHOSTANDALONE', 'PMNOSUCCESSOUTIRATHOSTANDALONE', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOSUCCESSOUTSBHOSPEECH', 'PMNOSUCCESSOUTSBHOSPEECH', 'CLT_PM_W_ERIC_GSMRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOATTOUTCNHHOCSNONSPEECH', 'PMNOATTOUTCNHHOCSNONSPEECH', 'CLT_PM_W_ERIC_UTRANRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOATTOUTCNHHOSPEECH', 'PMNOATTOUTCNHHOSPEECH', 'CLT_PM_W_ERIC_UTRANRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOSUCCOUTCNHHOCSNONSPEECH', 'PMNOSUCCOUTCNHHOCSNONSPEECH', 'CLT_PM_W_ERIC_UTRANRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOSUCCOUTCNHHOSPEECH', 'PMNOSUCCOUTCNHHOSPEECH', 'CLT_PM_W_ERIC_UTRANRELATION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMEULRLCUSERPACKETTHP', 'PMEULRLCUSERPACKETTHP', 'CLT_PM_W_ERIC_EUL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMEULDOWNTIMEMAN', 'PMEULDOWNTIMEMAN', 'CLT_PM_W_ERIC_EUL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMEULDOWNTIMEAUTO', 'PMEULDOWNTIMEAUTO', 'CLT_PM_W_ERIC_EUL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMEULRLCUSERPACKETTHP', 'PMSUMEULRLCUSERPACKETTHP', 'CLT_PM_W_ERIC_EUL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESEULRLCUSERPACKETTHP', 'PMSAMPLESEULRLCUSERPACKETTHP', 'CLT_PM_W_ERIC_EUL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMEULRLCTOTPACKETTHP', 'PMSUMEULRLCTOTPACKETTHP', 'CLT_PM_W_ERIC_EUL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESEULRLCTOTPACKETTHP', 'PMSAMPLESEULRLCTOTPACKETTHP', 'CLT_PM_W_ERIC_EUL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNODISCARDSDUDTCHHS', 'PMNODISCARDSDUDTCHHS', 'CLT_PM_W_ERIC_HSDSCH');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORECEIVEDSDUDTCHHS', 'PMNORECEIVEDSDUDTCHHS', 'CLT_PM_W_ERIC_HSDSCH');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMHSDLRLCUSERPACKETTHP', 'PMHSDLRLCUSERPACKETTHP', 'CLT_PM_W_ERIC_HSDSCH');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMHSDOWNTIMEMAN', 'PMHSDOWNTIMEMAN', 'CLT_PM_W_ERIC_HSDSCH');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMHSDOWNTIMEAUTO', 'PMHSDOWNTIMEAUTO', 'CLT_PM_W_ERIC_HSDSCH');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMHSDLRLCUSERPACKETTHP', 'PMSUMHSDLRLCUSERPACKETTHP', 'CLT_PM_W_ERIC_HSDSCH');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESHSDLRLCUSERPACKETTHP', 'PMSAMPLESHSDLRLCUSERPACKETTHP', 'CLT_PM_W_ERIC_HSDSCH');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMHSDLRLCTOTPACKETTHP', 'PMSUMHSDLRLCTOTPACKETTHP', 'CLT_PM_W_ERIC_HSDSCH');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESHSDLRLCTOTPACKETTHP', 'PMSAMPLESHSDLRLCTOTPACKETTHP', 'CLT_PM_W_ERIC_HSDSCH');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMRECEIVEDATMCELLS', 'PMRECEIVEDATMCELLS', 'CLT_PM_W_ERIC_VCLTP');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMTRANSMITTEDATMCELLS', 'PMTRANSMITTEDATMCELLS', 'CLT_PM_W_ERIC_VCLTP');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOFRLFORDRIFTINGUESPERDRNC', 'PMNOOFRLFORDRIFTINGUESPERDRNC', 'CLT_PM_W_ERIC_IURLINK');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOATTINCCNHHOCSNONSPEECH', 'PMNOATTINCCNHHOCSNONSPEECH', 'CLT_PM_W_ERIC_IURLINK');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOATTINCCNHHOSPEECH', 'PMNOATTINCCNHHOSPEECH', 'CLT_PM_W_ERIC_IURLINK');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOSUCCINCCNHHOCSNONSPEECH', 'PMNOSUCCINCCNHHOCSNONSPEECH', 'CLT_PM_W_ERIC_IURLINK');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOSUCCINCCNHHOSPEECH', 'PMNOSUCCINCCNHHOSPEECH', 'CLT_PM_W_ERIC_IURLINK');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMEDCHDATAFRAMESLOST', 'PMEDCHDATAFRAMESLOST', 'CLT_PM_W_ERIC_IURLINK');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMEDCHDATAFRAMESRECEIVED', 'PMEDCHDATAFRAMESRECEIVED', 'CLT_PM_W_ERIC_IURLINK');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMEDCHDATAFRAMEDELAYIUB', 'PMEDCHDATAFRAMEDELAYIUB', 'CLT_PM_W_ERIC_IURLINK');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMDLCREDITS', 'PMSUMDLCREDITS', 'CLT_PM_W_ERIC_IUBLINK');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMSQRDLCREDITS', 'PMSUMSQRDLCREDITS', 'CLT_PM_W_ERIC_IUBLINK');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESDLCREDITS', 'PMSAMPLESDLCREDITS', 'CLT_PM_W_ERIC_IUBLINK');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMULCREDITS', 'PMSUMULCREDITS', 'CLT_PM_W_ERIC_IUBLINK');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMSQRULCREDITS', 'PMSUMSQRULCREDITS', 'CLT_PM_W_ERIC_IUBLINK');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESULCREDITS', 'PMSAMPLESULCREDITS', 'CLT_PM_W_ERIC_IUBLINK');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMDLCREDITS', 'PMDLCREDITS', 'CLT_PM_W_ERIC_IUBLINK');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMULCREDITS', 'PMULCREDITS', 'CLT_PM_W_ERIC_IUBLINK');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMTOTALTIMEIUBLINKCONGESTEDDL', 'PMTOTALTIMEIUBLINKCONGESTEDDL', 'CLT_PM_W_ERIC_IUBLINK');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNORABESTABLISHFAILUREUECAPABILITY', 'COL_350', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMHSDCHJITTER', 'PMSUMHSDCHJITTER', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESHSDCHJITTER', 'PMSAMPLESHSDCHJITTER', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMHSEULJITTER', 'PMSUMHSEULJITTER', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESHSEULJITTER', 'PMSAMPLESHSEULJITTER', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMDCHDCHJITTER', 'PMSUMDCHDCHJITTER', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESDCHDCHJITTER', 'PMSAMPLESDCHDCHJITTER', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMHSDCHLATENCY', 'PMSUMHSDCHLATENCY', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESHSDCHLATENCY', 'PMSAMPLESHSDCHLATENCY', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMHSEULLATENCY', 'PMSUMHSEULLATENCY', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESHSEULLATENCY', 'PMSAMPLESHSEULLATENCY', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMDCHDCHLATENCY', 'PMSUMDCHDCHLATENCY', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESDCHDCHLATENCY', 'PMSAMPLESDCHDCHLATENCY', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMHSDCHDLRCVDELAY', 'PMSUMHSDCHDLRCVDELAY', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESHSDCHDLRCVDELAY', 'PMSAMPLESHSDCHDLRCVDELAY', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMHSEULDLRCVDELAY', 'PMSUMHSEULDLRCVDELAY', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESHSEULDLRCVDELAY', 'PMSAMPLESHSEULDLRCVDELAY', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMDCHDCHDLRCVDELAY', 'PMSUMDCHDCHDLRCVDELAY', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESDCHDCHDLRCVDELAY', 'PMSAMPLESDCHDCHDLRCVDELAY', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMHSDLDELAY', 'PMSUMHSDLDELAY', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESHSDLDELAY', 'PMSAMPLESHSDLDELAY', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMDCHDLDELAY', 'PMSUMDCHDLDELAY', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESDCHDLDELAY', 'PMSAMPLESDCHDLDELAY', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOFREDIRECTEDEMERGENCYCALLS', 'PMNOOFREDIRECTEDEMERGENCYCALLS', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSENTPACKETDATA1', 'PMSENTPACKETDATA1', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSENTPACKETDATAINCLRETRANS1', 'PMSENTPACKETDATAINCLRETRANS1', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMTOTALPACKETDURATION1', 'PMTOTALPACKETDURATION1', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOFPACKETCALLDURATION1', 'PMNOOFPACKETCALLDURATION1', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSENTPACKETDATA2', 'PMSENTPACKETDATA2', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSENTPACKETDATAINCLRETRANS2', 'PMSENTPACKETDATAINCLRETRANS2', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMTOTALPACKETDURATION2', 'PMTOTALPACKETDURATION2', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOFPACKETCALLDURATION2', 'PMNOOFPACKETCALLDURATION2', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSENTPACKETDATA3', 'PMSENTPACKETDATA3', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSENTPACKETDATAINCLRETRANS3', 'PMSENTPACKETDATAINCLRETRANS3', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMTOTALPACKETDURATION3', 'PMTOTALPACKETDURATION3', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOFPACKETCALLDURATION3', 'PMNOOFPACKETCALLDURATION3', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSENTPACKETDATA4', 'PMSENTPACKETDATA4', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSENTPACKETDATAINCLRETRANS4', 'PMSENTPACKETDATAINCLRETRANS4', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMTOTALPACKETDURATION4', 'PMTOTALPACKETDURATION4', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOFPACKETCALLDURATION4', 'PMNOOFPACKETCALLDURATION4', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSENTPACKETDATAHS1', 'PMSENTPACKETDATAHS1', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSENTPACKETDATAINCLRETRANSHS1', 'PMSENTPACKETDATAINCLRETRANSHS1', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMTOTALPACKETDURATIONHS1', 'PMTOTALPACKETDURATIONHS1', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOFPACKETCALLDURATIONHS1', 'PMNOOFPACKETCALLDURATIONHS1', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSENTPACKETDATAHS2', 'PMSENTPACKETDATAHS2', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSENTPACKETDATAINCLRETRANSHS2', 'PMSENTPACKETDATAINCLRETRANSHS2', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMTOTALPACKETDURATIONHS2', 'PMTOTALPACKETDURATIONHS2', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOFPACKETCALLDURATIONHS2', 'PMNOOFPACKETCALLDURATIONHS2', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSENTPACKETDATAHS3', 'PMSENTPACKETDATAHS3', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSENTPACKETDATAINCLRETRANSHS3', 'PMSENTPACKETDATAINCLRETRANSHS3', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMTOTALPACKETDURATIONHS3', 'PMTOTALPACKETDURATIONHS3', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOFPACKETCALLDURATIONHS3', 'PMNOOFPACKETCALLDURATIONHS3', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSENTPACKETDATAHS4', 'PMSENTPACKETDATAHS4', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSENTPACKETDATAINCLRETRANSHS4', 'PMSENTPACKETDATAINCLRETRANSHS4', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMTOTALPACKETDURATIONHS4', 'PMTOTALPACKETDURATIONHS4', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOOFPACKETCALLDURATIONHS4', 'PMNOOFPACKETCALLDURATIONHS4', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOIUSIGESTABLISHATTEMPTCS', 'PMNOIUSIGESTABLISHATTEMPTCS', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOIUSIGESTABLISHSUCCESSCS', 'PMNOIUSIGESTABLISHSUCCESSCS', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOIUSIGESTABLISHATTEMPTPS', 'PMNOIUSIGESTABLISHATTEMPTPS', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOIUSIGESTABLISHSUCCESSPS', 'PMNOIUSIGESTABLISHSUCCESSPS', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMNOINVALIDRABESTABLISHATTEMPTS', 'COL_351', 'CLT_PM_W_ERIC_RNCFUNCTION');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSECONDSWITHUNEXP', 'PMSECONDSWITHUNEXP', 'CLT_PM_W_ERIC_ATMPORT');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSAMPLESMEASUREDLOAD', 'PMSAMPLESMEASUREDLOAD', 'CLT_PM_W_ERIC_LOADCONTROL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMMEASUREDLOAD', 'PMSUMMEASUREDLOAD', 'CLT_PM_W_ERIC_LOADCONTROL');

insert into clt_pm_w_eric_map (COL_NAME, SHORT_COL_NAME, TAB_NAME)
values ('PMSUMSQRMEASUREDLOAD', 'PMSUMSQRMEASUREDLOAD', 'CLT_PM_W_ERIC_LOADCONTROL');

